### ISSUE TITLE
CC-BY-ND-4.0 is detected as CC-BY-4.0

### ISSUE THREAD

**Issue by benbalter** [benbalter/licensee#116]

**Comment by benbalter** [comment]
Testing locally, the two are `99.38%` similar. That means the only workaround would be to add and explicitly detected CC-BY-ND so that it's a higher match. I'm not sure I want to do that, as CC-BY-ND is a non-OSI-approved license. The other option is to explicitly detect it, but to detect it as "no-license", meaning we match the license, but don't return that the project is licensed, since it's a non-open-source license.

@mlinksva @bkeepers any strong opinions one way or the other here?

**Comment by getify** [comment]
CC-BY-ND may be non-OSI approved, but it's definitely valid by CC standards, which I'd argue ia deservedly a peer of OSI, not a lesser valid entity.

I use CC-BY-ND to license my book writing because this is typically required by publisher contracts to allow authors to CC their work. I know quite a few authors who use it. I'm working on my seventh published book that I've written and CC released on github. It's a big bummer if I can't have my authored works license-recognized on this platform. 

Additionally, the idea that it would literally say "no license" in the CC-BY-ND case is quite objectionable and the worst option...  because I would, as an unsuspecting visitor to such a repo, assume that "no license" means "no license at all", not the more nuanced "no OSI approved license that we prefer to see in this platform". I would strongly dislike the implication that CC-BY-ND is indistinguishable from there being no license at all, if for no other reason than to not mislead visitors.

At a bare minimum I'd request that case say something like "non-OSI" or "Custom" or "Unrecognized" or something like that.

If I put a LICENSE.TXT file in the repo, that's very different from not putting anything at all, even if the contents of it are not something the platform wishes to endorse/support.

**Comment by mlinksva** [comment]
GitHub doesn't display anything if it can't positively identify a license, eg https://github.com/getify/You-Dont-Know-JS (CC-BY-NC-ND-3.0). In general that's the correct behavior. We can't currently positively identify a huge number of licenses (over 600 from CC alone, and hundreds if not thousands of variations on various template-like open source licenses). Another usually correct behavior would be to just link to the LICENSE file that we cannot positively identify, eg "License", or "Unrecognized" ... "Custom" or "non-OSI" we could not be certain of.

licensee should also output something like "unrecognized" when it finds a license file but can't positively identify the license. "no license" is not likely to be an accurate statement. I think this is a separate issue though. I don't think it has been noted before ([search](https://github.com/benbalter/licensee/issues?utf8=%E2%9C%93&q=%22no%20license%22)) but I'll file in a moment.

How to avoid the false positive this issue is directly about -- I'd rather not add the CC licenses that don't currently qualify to be cataloged in choosealicense.com (which licensee vendors) just to fix this issue with the alacrity this issue should be fixed because that means changing the [criteria](https://github.com/github/choosealicense.com/blob/b3963610366146074f5493d9207a01bf3b59c852/CONTRIBUTING.md#adding-a-license) for cataloging licenses in choosealicense.com which should be done thoughtfully.

@benbalter I wonder if licensee should have its own collection of false-positive-avoidance license texts, which could be added to as needed to hack around false positives that can't be solved by adjusting confidence threshold? If that's a bad idea, I'll go ahead and add the 4 non-qualifying CC 4.0 International licenses to choosealicense.com in some non-disruptive way. Let me know. 😄

**Comment by benbalter** [comment]
@getify thanks for the additional context - very helpful. I'd like to distinguish two things:

1. Licensee and GitHub - Licensee is an open source project, designed to detect open source software licenses. It can signal if a license file is found, and if that license file matches a known license, but how that information is presented to end users (on GitHub or elsewhere), is ultimately out of Licensee's control (but this conversation can certainly inform GitHub's open source team).

2. Open source licenses and creative commons licenses - Licensee was created [to detect open source software licenses](https://github.com/benbalter/licensee#the-problem). While creative commons licenses are certainly *open* licenses, they're not always open source licenses (e.g., no derivative works), and they're not software licenses. 

With those constraints in mind, there's three reasons why I don't think expanding CC license detection is a good idea:

1. Right now, if a license is detected (e.g., if `LicenseFile#match` returns a value other than `nil`), a downstream user can assume that that project is open source. Allowing non-open-source licenses, while definitely possible, would require the downstream user to introspect that license to determine what rights, if any, they are granted.

2. Licensee gets its license information from choosealicense.com, which has a large, specialized community that can provide and vet license metadata. Vendoring licenses from elsewhere would require us to create that metadata ourselves, which may introduce inaccuracies or create legal risk.

3. Licensee is intended to help encourage open source licensing and to help standardize that experience. Expanding Licensee to detect non-open source licenses feels out of scope (and potentially antithetical) at this time.

That said, I think there are two things we can do here:

1. Vendor the non-open source creative commons licenses into licensee and use them to prevent false positives. While I don't think `LicenceFile#match` should return `CC-BY-ND` in this case, I do think that information can be used to ensure that method doesn't return a different CC license, when we know it to be wrong.

2. Improve how GitHub handles licenses it doesn't know. This can be saying "unknown" or "other", etc. and linking to the license text. Today, I believe no license information is displayed in this case.

How does that sound?

**Comment by getify** [comment]
I can understand why the scope of licensee would want to protect its most narrow use-case: "OSI approved open license" detection. I'm not trying to suggest anything that would break that use-case.

I've never used this library, so forgive my ignorance here, but... is it possible for there to be two layers of detection? Licensee could offer `LicenseFile#match` for the strict OSI matching case, and `LicenseFile#looseMatch` or something like that, for the looser definition of "recognizable licenses" (especially open-but-non-OSI ones like CC-BY-ND).

It seems reasonable to me that this looser-matching still logically makes most sense encapsulated in a library like licensee, rather than possibly leaving a client of the library to invent its own ad hoc logic for doing so, and then some other tool or site wants to do the same but they have to invent their own again, etc.

Of course, that suggestion is based on an assumption that at least one client (like GH) *wants* to handle more license detection than just strictly OSI-approved licenses. I hope they do. And I can certainly imagine other sites/tools finding value in such a capability.

The two layer (strict/loose) matching concept would mean that clients which only want **strictly open** license matching, can do so easily, and those who'd like to use the more broad license detection matching can do so also.

The question then becomes: if this looser matching did exist, would a client like GH want to use it?

**Comment by libeclipse** [comment]
Update: `CC BY-NC 4.0` is also mislabelled as `CC-BY-4.0`. Unlike ND, NC is undoubtedly an open-source licence.

**Comment by mlinksva** [comment]
@libeclipse tangential to this issue, but FWIW NC is undoubtedly _not_ an open-source license, see 6 of https://opensource.org/osd-annotated or for non-software 2.1.8 of http://opendefinition.org/od/2.1/en/

@benbalter idea on fixing this bug: look for strings "NonCommercial" or "NoDerivatives" in license, stop detection if found.

**Comment by getify** [comment]
Is this issue tracking only the bug (misidentifying)?

> licensee should also output something like "unrecognized" when it finds a license file but can't positively identify the license. "no license" is not likely to be an accurate statement. I think this is a separate issue though.

Do we need a separate issue for making `licensee` return "unrecognized" instead of "no license"? Or can that be fixed at the same time here?

-------

Would `licensee` consider another separate bug (or even PR) for the idea of "loose matching" I mentioned earlier in the thread, specifically to identify the CC licenses alongside OSI?

Or should I just file an issue at github about displaying a link to the license in place of it not being able to detect a name? Come to think of it, the link would be helpful in all cases even if it's name is recognized, so maybe adding the link and have it just say "LICENSE" when it doesn't know another name?

**Comment by willin** [comment]
but how about writings? like gitbook projects...

**Comment by libeclipse** [comment]
Yeah, that's something I use those specific CC licences for. Essays,
writings, written projects.

**Comment by willin** [comment]
@benbalter  https://github.com/js-cool/leader.js.cool ？？？

**Comment by mlinksva** [comment]
@willin the new code isn't deployed on github.com yet, and it won't automatically re-detect licenses on every one of millions of repos when it is. If you send a support request via https://github.com/contact asking for re-detection of the license of your repo they can let you know when it's done.
