### ISSUE TITLE
usually inaccurate output: License file: LICENSE.txt License: no license

### ISSUE THREAD

**Issue by mlinksva** [benbalter/licensee#118]
As [noted](https://github.com/benbalter/licensee/issues/116#issuecomment-248475953) if licensee can find a license file but can't positively identify the license, it outputs "no license", which is usually inaccurate. "Unknown" or "Unrecognized" would be accurate. Example:

```
script/git-repo https://github.com/getify/You-Dont-Know-JS
License file: LICENSE.txt
License: no license
```

In some cases licensee does output "Unknown" and maybe "Not detected" (see https://github.com/benbalter/licensee/blob/3120af283634fd3bd3731f2abe4167c6eba216f0/bin/licensee#L20 ... I haven't followed when this code is executed), but obviously not in the above example.

**Comment by benbalter** [comment]
This is fixed on `master`, at least for the command line-output.

```
script/git-repo https://github.com/getify/You-Dont-Know-JS
License file: LICENSE.txt
License: Not detected

Here's the closest licenses:
* CC-BY-SA-4.0 similarity: 57.12%
* GPL-2.0 similarity: 40.39%
* LPPL-1.3c similarity: 36.35%
```

>  it outputs "no license", which is usually inaccurate. "Unknown" or "Unrecognized" would be accurate. 

To be clear, that was an artifact of a quick command-line diagnostic tool (now fixed with expanded output). Internally, Licensee has the concept of the "matched file" and the "matched license". If there's a matched file, that means it found a license file (it has a license or copyright notice). In that case, `MatchedFile#match` would return `nil` if it wasn't matched, or the License, if it was (the actual output is up to the platform implementing the interface (e.g., GitHub, command line)).
