### ISSUE TITLE
Fail detection when appended content is too big

### ISSUE THREAD

**Issue by eskatos** [benbalter/licensee#128]
> If we still can't match the license, we use a fancy math thing called the Sørensen–Dice coefficient, which is really good at calculating the similarity between two strings. By calculating the percent changed from the known license to the license file, you can tell, e.g., that a given license is 95% similar to the MIT license, that 5% likely representing legally insignificant changes to the license text.

The issue with this strategy is that if, according to a license, you need to append notices about included/bundled libraries to a LICENSE file, then the appended notice may be too big, sometimes bigger than the actual licence, and cross the threshold.

Examples:
- https://github.com/apache/spark/blob/master/LICENSE
- https://github.com/gradle/gradle/blob/master/LICENSE
- https://github.com/apache/zest-java/blob/develop/LICENSE.txt
- https://github.com/apache/accumulo/blob/master/LICENSE
- etc...

**Comment by benbalter** [comment]
>  according to a license, you need to append notices about included/bundled libraries to a LICENSE file

@eskatos can you provide some examples of licenses that require the attribution be append to the license file itself?

**Comment by eskatos** [comment]
Sure. ASF instructions to apply Apache 2 License: http://www.apache.org/dev/licensing-howto.html#permissive-deps

**Comment by benbalter** [comment]
@mlinksva have you seen this before? Any thoughts on how best to handle this?

**Comment by mlinksva** [comment]
I don't think any license says "you need to append notices about included/bundled libraries to a LICENSE file" ... said notices could be provided in a different file.

I've seen the practice of appending subcomponent licenses to the LICENSE file but didn't know it is following an ASF instruction. Seems that instruction is not precise enough to allow for machine detection.

I could imagine licensee doing something to accommodate this convention -- maybe something like if Apache-2.0 with long text following, ignore long text if it contains string "subcomponent". Not at all sure that's a good idea.

Otherwise we can continue to not detect a license with a bunch of extra text. At least we won't get false positives.

If machine detection is important, longer term it'd be nice if Apache updated its recommendation to document subcomponent notices in a machine readable file, probably SPDX.

**Comment by eskatos** [comment]
> I could imagine licensee doing something to accommodate this convention -- maybe something like if Apache-2.0 with long text following, ignore long text if it contains string "subcomponent". Not at all sure that's a good idea.

This could work for the bunch of ASF projects and others out of the ASF that do just that.

Yes, SPDX would be nice but if/when ASF recommends it, it will take a lot of time for projects to change their license data.

**Comment by eskatos** [comment]
> @eskatos can you provide some examples of licenses that require the attribution be append to the license file itself?

@benbalter I was not referring to attribution but to bundled components notices.

About attribution, with the example LICENSE files I linked in the issue, licensee take the first bundled component attribution as the project attribution. 

For example, here is the output for Apache Zest:
```
user@host ~/zest-java $ licensee
License file: LICENSE.txt
Attribution: Copyright 2014 jQuery Foundation and other contributors.
License: Not detected

Here's the closest licenses:
```

Apache Zest bundles jQuery but the attribution is wrongly detected in this case. I tried to add the Apache License boilerplate with the correct attribution in the README of that project but it didn't help. That's probably a different issue than the length of appended content though.
