### ISSUE TITLE
Regressions with v8.8.0

### ISSUE THREAD

**Issue by pchaigno** [benbalter/licensee#173]
With Licensee v8.8.0, a few licenses are not recognized anymore:
- [Anomareh/PHP-Twig.tmbundle](https://github.com/Anomareh/PHP-Twig.tmbundle/blob/master/LICENSE)
```
$ licensee _8.7.0_ PHP-Twig.tmbundle/
License file: LICENSE
License hash: 437a5288fec1cfe57fccf1065702cbf8c1b2dd3b
Attribution: Copyright (c) 2014, Andrew Fricke
License: BSD 3-clause "New" or "Revised" License
Confidence: 97.07%
Method: Licensee::Matchers::Dice
```
- [guillermooo/dart-sublime-bundle](https://github.com/guillermooo/dart-sublime-bundle/blob/master/LICENSE)
```
$ licensee _8.7.0_ dart-sublime-bundle/
License file: LICENSE
License hash: 4c585ff8dede0e3422b48c1a08af8d3a2520a0aa
Attribution: Copyright (c) 2014, Guillermo Lpez-Anglada. All rights reserved.
License: BSD 3-clause "New" or "Revised" License
Confidence: 96.23%
Method: Licensee::Matchers::Dice
```
- [lsf37/Isabelle.tmbundle](https://github.com/lsf37/Isabelle.tmbundle/blob/master/LICENSE.md)
```
$ licensee _8.7.0_ Isabelle.tmbundle/
License file: LICENSE.md
License hash: 1955ed00933a17ac6195425a3b2f7f13ac35a251
Attribution: Copyright (c) 2014 Gerwin Klein and contributors.
License: BSD 2-clause "Simplified" License
Confidence: 96.23%
Method: Licensee::Matchers::Dice
```
- [mokus0/Agda.tmbundle](https://github.com/mokus0/Agda.tmbundle/blob/master/LICENSE)
```
$ licensee _8.7.0_ Agda.tmbundle/
License file: LICENSE
License hash: a685013dbb5bf3f03da76bc9a787daa6d63a1207
Attribution: Copyright (c) 2014 James Cook
License: BSD 3-clause "New" or "Revised" License
Confidence: 95.12%
Method: Licensee::Matchers::Dice
```
There may be a few more in [Linguist's submodules](https://github.com/github/linguist/tree/master/vendor/grammars).
I'm not able to tell if this is expected behavior. Could it be because the first lines (title & attribution) are not considered anymore when computing the percentage, and it falls below 95%?

**Comment by benbalter** [comment]
Technically technically, these are (slightly) modified licenses. Take a look at the third clause of Anomareh/PHP-Twig.tmbundle's license. What's in the file:

> The names of its contributors may not be used to endorse or promote products
  derived from this software without specific prior written permission.

And the same clause in guillermooo/dart-sublime-bundle

> Neither the name of this software nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

And from lsf37/Isabelle.tmbundle:

> Neither the name of the author nor the names of his contributors may be used to endorse or promote products derived from this software without specific prior written permission.

The real license:

> Neither the name of the copyright holder nor the names of its contributors may be used
  to endorse or promote products derived from this software without specific
  prior written permission.

I'm not sure why there's the variation there. Maybe @mlinksva knows?

That said, it's a small enough change that it should be detected. The underlying problem is that the BSD metadata title differs from the in-license title, which should be fixed by https://github.com/benbalter/licensee/pull/174 (which properly detects the four licenses above).

**Comment by mlinksva** [comment]
There's a ton of variation in that part of the BSD licenses in particular because the copyright holder in the past was explicitly named (starting with UC Berkeley), treated as a fill-in field, and made re-usable without the fill-in field with various wording.

https://en.wikipedia.org/wiki/BSD_licenses has the basic backround. A paper (doi: 10.1007/978-3-319-17837-0_14) that's sadly not open access backs this up with lots of data and finds that MIT licenses are even more variable.

SPDX is documenting some of this variability in a way that might be reusable, eg https://github.com/spdx/license-list-XML/blob/2c50d60c21710bd737582e438c5639695b10e367/src/BSD-2-Clause.xml#L27-L31

**Comment by pchaigno** [comment]
Thank you both for the information :smiley: 

I'm closing since #174 fixes the issue with the four repositories above.
