### ISSUE TITLE
License file containing Apache-2.0 not being matched

### ISSUE THREAD

**Issue by willbar** [benbalter/licensee#191]
If you run ```licensee``` against https://github.com/twitter/twitter-text/blob/master/LICENSE it doesn't match the Apache-2.0 license.

**Comment by benbalter** [comment]
The issue appears to be that the author took the Apache boilerplate (normally found at the bottom of the license and applied to individual files) and added it to the top of the LICENSE file.

**Comment by mlinksva** [comment]
https://github.com/twitter/twitter-text/blob/master/LICENSE doesn't include the appendix at the end of the text and prepends notice text that's usually used in file headers, NOTICE, or README. I wouldn't be surprised for it to not match Apache-2.0 or any license, but seems that it matches the Apache-2.0 derived and recently added ECL-2.0 license:

```
$ script/git-repo  https://github.com/twitter/twitter-text
License file: LICENSE
License hash: e19a9d85daf301edc053c9617910d0f730ec0dd6
Attribution: Copyright 2011 Twitter, Inc.
License: Educational Community License v2.0
Confidence: 96.04%
Method: Licensee::Matchers::Dice
```

One approach to fixing might be along the lines of [how](https://github.com/benbalter/licensee/blob/66a3487c37246682decd8dcbb437196fcc4e2e76/lib/licensee/matchers/dice_matcher.rb#L30) we avoid detecting CC NC or ND licenses as CC-BY-4.0 or CC-BY-SA-4.0, but instead of failing a detection if a license text includes certain strings, fail detection of ECL-2.0 if the license text does not include certain strings (probably "Educational Community License").

That would have the same effect as removing the vendored ECL-2.0 text, which obtains what I'd expect:

```
$ script/git-repo  https://github.com/twitter/twitter-text
License file: LICENSE
License hash: e19a9d85daf301edc053c9617910d0f730ec0dd6
Attribution: Copyright 2011 Twitter, Inc.
License: Not detected
```
