### ISSUE TITLE
The 4-clause BSD license is not detected

### ISSUE THREAD

**Issue by okeuday** [benbalter/licensee#195]
The license was previously detected, but appears to no longer be detected after recent changes.

**Comment by mlinksva** [comment]
If it was previously detected it was a false positive, because BSD-4-Clause isn't in https://github.com/benbalter/licensee/tree/b94e3917eed0c6f038c352bce05732c5104d83b9/vendor/choosealicense.com/_licenses

That could be addressed via https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license
