### ISSUE TITLE
Not detected as GPL-3

### ISSUE THREAD

**Issue by sjackman** [benbalter/licensee#218]
https://github.com/bcgsc/abyss/blob/master/LICENSE as GPL-3, but `licensee` does not, which is odd, because I thought GitHub uses `licensee` for its license detection.
```
❯❯❯ curl -O https://raw.githubusercontent.com/bcgsc/abyss/master/LICENSE
❯❯❯ licensee
License: Other
Matched files: ["LICENSE"]
LICENSE:
  Content hash: dd0ab75fcd5544191cc2b0a5a79fb06db4c7f455
  License: Other
```

**Comment by mlinksva** [comment]
Licensee has gotten stricter so as to avoid more false positives since that LICENSE file was pushed on 2016-09-14. The notice prepended to the file will cause it to not detect the license now.

**Comment by sjackman** [comment]
That LICENSE file contains the GPL-3 license in its entirety without modification. It would be helpful for `licensee` to detect and report that.

**Comment by sjackman** [comment]
Alternatively, how could that `LICENSE` file be modified so that `licensee` detects it as GPL-3?

**Comment by mlinksva** [comment]
It does contain the entire license, but it also contains other text. We can't tell whether that other text is innocuous or attempts to contradict the license in some form, so the safest thing is to not detect.

Licensee should detect the LICENSE file as GPL-3.0 if you remove the notice prepended to the license. The notice could go somewhere else, eg README or  source file comments.

However, the most recent version of licensee still will not detect the repo as a whole under GPL-3.0 because it contains both a LICENSE and a COPYRIGHT file, and again taking the safest route, the most recent licensee won't positively identify a single license if it detects multiple potential license files. Again you could move the contents of COPYRIGHT, eg into README, or rename to NOTICE or CREDITS something else.

**Comment by mlinksva** [comment]
Or I suppose debian/copyright :smile:

**Comment by sjackman** [comment]
Thanks for the help, Mike.

**Comment by Luke1410** [comment]
@mlinksva First of all thanks for the great work on this project.
I've however to state that I can't really follow your arguments with regards to being so strict on no notes being allowed in a license file and for Licensee to take the "safest" bet. How is it (legal-wise) safer to not identify a license as the GPL-3.0 license just because someone added a simple note to the end of the file as in: "See the readme.txt file for further notes/details." while on the other side you are actively suggesting to make clarifying statements on license issues in the readme file?

In my particular case I'd like to add a simple note/reference at the end of the otherwise completely unmodified MIT-license asking for additional (non-legal-binding) gestures of good faith. Nothing of which is legally binding, but I'd still like to keep at least a short reference to these in the license file.
see https://github.com/SLikeSoft/SLikeNet/commit/81eb2eeea0b3fc7765ce67485509caf6dae2a46a for a concrete example of the initial simplified license text which I tried to use with Licensee.

Unfortunately, Licensee won't then determine the license file as the MIT-license with that note anymore (resulting in GitHub not listing the project as one under the MIT-license which in-fact it is).

To be clear: I really appreciate all the work you (i.e. the team) did but how I'm really having a hard time that you argue on the one side to put additional license information/clarifications into the readme file while on the other side you don't allow adding even a reference to these additional clarifications into the license file then. To be honest, this doesn't make much sense to me. :-)
