### ISSUE TITLE
confidence_threshold not accurately reflected in dice matcher

### ISSUE THREAD

**Issue by jpeddicord** [benbalter/licensee#226]
Test case:

```ruby
#!/usr/bin/env ruby
require 'licensee'
Licensee.confidence_threshold = 85
p = Licensee.project(ARGV[0])
puts "#{p.license.key} #{p.matched_file.confidence}"
```

Running this against `https://raw.githubusercontent.com/pgbouncer/pgbouncer/master/COPYRIGHT`, for example, yields `other`. However, lowering the confidence threshold to 80 nets `isc 90.41095890410958`. This feels strange to me; a threshold of 90 should have even worked there, right? The highest integer threshold I'm able to use is 81.

This is not unique to that license file; it's just a good demonstration. I also saw this happening on another license that _should_ have matched at 85% confidence, yet it refused to identify until confidence was lowered around 60 or so.

**Comment by jpeddicord** [comment]
In fact, looking at those numbers again... 90% of 90 is 81 -- right where things stopped working. This makes me wonder if the default threshold of 98% is actually effectively 99%; even more strict. I'm poking around to see if this threshold is being over-calculated somewhere.

**Comment by benbalter** [comment]
@jpeddicord sorry I never responded to you here. Did you ever track down the root cause? Looking into this myself now as well.

**Comment by jpeddicord** [comment]
No worries, I got distracted from this issue myself. This is from memory of when I was debugging:

In [content_helper's max_delta](https://github.com/benbalter/licensee/blob/master/lib/licensee/content_helper.rb#L35), the math there is set up to report a delta based on the length of a string. However, in dice matching (similarity method a few lines down), the strategy is **double** the length over the overlap size. This is a correct Sørensen-Dice approximation, and licensee generates correct similarities. The problem is that max_delta too aggressively filters out values.

So what's the fix? 2 characters:

    @max_delta ||= (length * Licensee.inverse_confidence_threshold).to_i

becomes

    @max_delta ||= (length * Licensee.inverse_confidence_threshold).to_i * 2

However, making this change leaves you with a problem:

A fair amount of unit tests and behaviors break, because licensee was tuned for this behavior. This is the hard part: you have a choice of making this fix and enabling more flexible thresholds, but then the default threshold needs tuning to make tests work again. This is where I recall stopping, as it seemed to be a more invasive change.

Slight tangent: max_delta is actually computed based on string (character) lengths, while similarity is computed based on counts of words. This will get you _slightly_ different values for similarity and max_delta on the same strings. It's mostly only going to present itself as an issue if you get a license where someone replaced (e.g.) "owner" with "this-person-with-a-really-long-one-word-name" -- max_delta would filter this out while similarity may still match. Not critical and probably worth discussing outside this issue.

**Comment by mlinksva** [comment]
I played around with this and made #242 to explore how to address.

As far as I can tell, max_delta is serving two purposes: (1) avoid work of calculating similarity of licenses that just aren't going to be matches, and (2) filter out some licenses that are going to be matches if we don't filter them out, because they're long enough that a fair amount of text changes don't drive down similarity very much.

(2) is what is causing the unintuitive result documented in this issue, where you set a confidence level and don't get as even potential matches licenses that you know have similarity above the confidence level you've selected.

#242 avoids the necessity of (2) by scaling dissimilarity with content size. Just an idea. :smile:

Here are command line results for #242  _with confidence threshold set to 90_:

```
$ script/git-repo https://github.com/pgbouncer/pgbouncer
License: Other
Matched files: ["COPYRIGHT"]
COPYRIGHT:
  Content hash: 05d71d5a7b5a26dab27ff0f7eff7f3ae7e1a36c8
  License: Other
  Closest licenses:
    * ISC similarity: 80.40%
    * PostgreSQL similarity: 32.46%
    * MIT similarity: 27.55%
```
Set confidence threshold to 80, you get ISC detected.

Note ISC's similarity is 80% rather than 90% because it is being lightly penalized already by dissimilarity scaling.
