### ISSUE TITLE
SPDX ID is lower case in JSON output

### ISSUE THREAD

**Issue by sschuberth** [benbalter/licensee#282]
Using version 9.9.0.beta.3, `detect --json` creates output like

    ...,"matched_license":"apache-2.0"}]}

i.e. the SPDX ID starts with a lower case letter, whereas running `detect` (without `--json`) on the same file results in

    License:        Apache-2.0

i.e. the SPDX ID is capitalized.

I believe @benbalter has been involved in a discussion on the *spdx-tech* mailing list that, while SPDX ID comparison should ignore case, the display of SPDX IDs should match the capitalization from [the list](https://spdx.org/licenses/).

**Comment by benbalter** [comment]
@sschuberth internally, and in the Ruby API we used a down-cased (case insensitive) version of the SPDX ID which we call the "license key". The idea being, that generally speaking, keys aren't assumed to be case sensitive, and when doing string comparison, it's easier when everything's the same case (e.g., when used in URLs, file systems, API or form parameters, etc.). 

As you know SPDX IDs are case sensitive, even though no two IDs would occupy the same case insensitive namespace. In the project_file hash, [we return the license key](https://github.com/benbalter/licensee/blob/0d87ecc0f59189a670597d001641abf775433362/lib/licensee/project_files/project_file.rb#L69), rather than including the full license object, and all of its metadata multiple times for each matched file. (If you think that's preferable, we can return the full hash instead of the key, but it would result in a larger payload, I'm fine either way).

Right now, if you want the SPDX ID of a matched file, I believe the easiest way would be to find the license in the `licenses` key with the same ID, and then retrieve it's SPDX ID property... as I say that... it may make more sense to return the entire hash?

**Comment by sschuberth** [comment]
> it may make more sense to return the entire hash?

I don't think so, too much potential duplication, and I like the idea of `licenses` being a summary of found licenses.

But could you elaborate what things would break if the `key` was the (case sensitive) `spdx_id`? I mean, is there value in keeping both  `key` *and* `spdx_id`, or could the value of  `key` just be the one of `spdx_id`, and `spdx_id` be dropped?

Anyway, now that I understand how it's supposed to work, I can easily do that extra lookup to get the SPDX ID for a license key.

**Comment by mlinksva** [comment]
I think it'd be reasonable to only ever output the cased SPDX ID. That's what the world has settled on.

**Comment by sschuberth** [comment]
Thanks for this @mlinksva. I anyway realized that the `key` field is not really a key and `licenses` is not a map you could use this key on, but `licenses` is an array which you have to iterate to look for the `key`. If you need to iterate anyway, you can as well search `licenses` by `spdx_id` instead of `key`, so the change done by @mlinksva does not add any performance penalty in this lookup.
