### ISSUE TITLE
Performance Report 

### ISSUE THREAD

**Issue by Nosferican** [benbalter/licensee#306]
### Performance Report

The case study is between licensee and [PackageEvaluator](https://github.com/JuliaCI/PackageEvaluator.jl) script for registered Julia packages.

### Data

Out of the packages and detected licenses from [PackageEvaluator Website](https://pkg.julialang.org/) for registered Julia packages 100/1,759 did not match. The mismatches are [here](https://docs.google.com/spreadsheets/d/1piODfniwwLU_1JvyJD8huh1u3rlUvRiZChOxyXyK-_o/edit?usp=sharing) (updated 2018-06-13).

### Specifics
Licensee was ran on the Julia package repositories and the top probability license was selected. 

### Actionables
Hope this information helps to continue improving the project.

**Comment by mlinksva** [comment]
Hi @Nosferican thanks for posting this. What version of licensee did you use? I suspect fairly old, as the very first entry (https://github.com/Algocircle/Cascadia.jl) shows licensee detecting MIT, but any semi-recent version would not because the `LICENSE` file has a lot more than just the MIT license.

PackageEvaluator's license detection probably works for lots of packages, but it's not robust at al. I don't know Julia, but it's pretty obvious what is going on:

- https://github.com/JuliaCI/PackageEvaluator.jl/blob/3dbc8169e9d26aef36ceb97e3175465cebf2f2ec/src/prepjson.jl#L50-L57
- https://github.com/JuliaCI/PackageEvaluator.jl/blob/3dbc8169e9d26aef36ceb97e3175465cebf2f2ec/src/prepjson.jl#L17-L27
- https://github.com/JuliaCI/PackageEvaluator.jl/blob/3dbc8169e9d26aef36ceb97e3175465cebf2f2ec/src/constants.jl#L14-L54

It reports the first entry as MIT because it looks for MIT first and the first example's license file does include the text of the MIT license (but that's not all it includes) and PackageEvaluator sees this based on matching just one of these short regexes (from the third file above):

```julia
("MIT",[
                    r"mit license",
                    r"mit expat license",
                    r"mit \"expat\" license",
                    r"permission is hereby granted, free of charge,"]),
```

Obvious this is going to cause some false positive identifications of MIT, such as when other terms are included in a LICENSE file.

It would be very useful to compare licensee detections to detections from other tools that try to be robust. Unfortunately I don't think there's much that can be gleaned from a comparison to Julia PackageEvaluator output. I don't intend this as a criticism of PackageEvaluator -- I'm sure it's authors did the simplest thing that works much of the time, and that may well be the right decision for whatever their needs are.

**Comment by mlinksva** [comment]
By the way @Nosferican I noticed that you posted this to https://github.com/JuliaCI/PackageEvaluator.jl/issues/205 as well and someone there pointed out that you've got licensee identifying https://github.com/DynareTeam/Dynare.jl as Unlicense. This again makes me think you're using a very old version of licensee. I see you also mention in that issue "work on a standard machine readable metadata schema in project.toml" -- I urge you to use SPDX license expressions as the permissible values, as lots of programs already know how to deal with those and they are unambiguous -- most of the time an expression will just be a single identifier such as "Apache-2.0" (simple, but there are lots of ways to come up on one's own about how to write that fact).

**Comment by mlinksva** [comment]
Or maybe you're using a current version of licensee and taking "closest" to mean something other than intended. You write:

> Licensee was ran on the Julia package repositories and the top probability license was selected.

Output of licensee 9.9.1:

```
$ script/git-repo https://github.com/DynareTeam/Dynare.jl
License:        NOASSERTION
Matched files:  LICENSE.md
LICENSE.md:
  Content hash:  10d088666241c6e88aafb51d721d4b78a275c221
  License:       NOASSERTION
  Closest licenses:
    Unlicense similarity:   38.92%
    Zlib similarity:        34.90%
    PostgreSQL similarity:  33.75%
```

NOASSERTION is what licensee is saying here. Maybe we should change "Closest licenses" to something else to warn against taking one of them as licensee saying it has detected one of them.

**Comment by Nosferican** [comment]
Thanks for the information. I used `v9.9.1` choosing the top closest license as a best guess. Will be examining some of the cases to develop a better classifier (maybe using the similarity and some labels). PackageEvaluator is design exclusively for Julia packages, but I wanted to see the relative performance compared to a more general case tool. I am quite happy with Licensee. I imagine that there might be some potential insight from that sample that can be used to improve the general error of licensee for other languages that haven't been been explored.

**Comment by mlinksva** [comment]
Made a small change in #307 that hopefully will make it less likely for anyone to take "closest" as "best guess". I don't think there's anything else immediately actionable, so closing. Thanks again for opening the issue, very interesting!
