### ISSUE TITLE
NetBSD style 2-clause BSD license not detected

### ISSUE THREAD

**Issue by rhdunn** [benbalter/licensee#323]
Running detect on https://github.com/espeak-ng/espeak-ng fails to detect `COPYING.BSD2` as the bsd-2-clause license. It gives the following output for that file:
```
COPYING.BSD2:
  Content hash:  fe2ee5f70e7ea744625c2b8ee84fe4fb83893839
  License:       NOASSERTION
  Closest licenses:
    BSD-2-Clause similarity:        96.08%
    BSD-3-Clause similarity:        89.09%
    BSD-3-Clause-Clear similarity:  85.59%
```

Running diff on the BSD2 license gives:
```
$ cat COPYING.BSD2 | licensee diff --license=bsd-2-clause
Comparing to BSD 2-Clause "Simplified" License:
Input Length:      1228
License length:    1222
Similarity:      96.08%
diff --git a/LICENSE b/LICENSE
index 62e1dc0..e538278 100644
--- a/LICENSE
+++ b/LICENSE
@@ -1,14 +1,14 @@
redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met: {+1.+} redistributions
of source code must retain the above copyright notice, this list of conditions
and the following disclaimer. {+2.+} redistributions in binary form must reproduce
the above copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the distribution. this
software is provided by the [-copyright holders-]{+netbsd foundation, inc.+} and contributors [-"as is"-]{+as is''+} and
any express or implied warranties, including, but not limited to, the implied
warranties of merchantability and fitness for a particular purpose are
disclaimed. in no event shall the [-copyright holder-]{+foundation+} or contributors be liable for any
direct, indirect, incidental, special, exemplary, or consequential damages
including, but not limited to, procurement of substitute goods or services; loss
of use, data, or profits; or business interruption however caused and on any
theory of liability, whether in contract, strict liability, or tort including
```

The file text was taken from the license text in the NetBSD getopt.c file comment at https://github.com/espeak-ng/espeak-ng/blob/master/src/compat/getopt.c.

**Comment by mlinksva** [comment]
If you get rid of the mixed single/backtick quotes and replace numbered bullets with asterisks (both of which licensee arguably ought to normalize), the match is still at 97.51% (below the 98% threshold).

FWIW the NetBSD variation is treated as a distinct license in the SPDX list: https://spdx.org/licenses/BSD-2-Clause-NetBSD.html ... it might be worth looking into https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license (from which licensee vendors license texts).

**Comment by mlinksva** [comment]
On 2nd thought I don't think it would be a good idea to add BSD-2-Clause-NetBSD to choosealicense.com ... licenses with hardcoded copyright holders aren't really appropriate for copy-paste into your own project that the site encourages, and licenses with a bunch of fill-in fields are very hard for licensee to ever detect.

A couple changes have been merged which would make some other aspects of this text easier to detect (#324, #325) but I think the way it might eventually be detected for sure is to eventually have licensee utilize all of the licenses cataloged by SPDX, this being one of them, but that's a much longer term project, so I'm going to close this issue rather than wait for stalebot to do so, since I don't think there are any other near term actions to take from it.

Thanks for filing the issue @rhdunn! 🙇
