### ISSUE TITLE
AGPLv3 not detected

### ISSUE THREAD

**Issue by spixi** [benbalter/licensee#345]
In some repos the AGPLv3 is not detected, for example:
https://github.com/aerospike/aerospike-server
https://github.com/diaspora/diaspora
https://github.com/instructure/rollcall-attendance
https://github.com/trailofbits/rattle
https://github.com/soedinglab/uniclust-pipeline
https://github.com/instructure/canvas-planner

**Comment by mlinksva** [comment]
Most of these have multiple files with license or copyright in their names. Licensee doesn't have a way of knowing which is the applicable license, so says 'other'.

However, for these two repos it might be worth [contacting support](https://github.com/c) and asking them to re-run license detection:

- I can't tell why the license for https://github.com/trailofbits/rattle wouldn't have been detected
- https://github.com/soedinglab/uniclust-pipeline includes a bunch of markup that results in the current licensee code detecting AGPL-3.0 just above the minimum threshold. It's likely that repo's license hasn't been re-detected in a very long time; the LICENSE file hasn't changed since 2016 and licensee may have gotten better at normalizing stuff found in markdown since then. Another option to trigger re-detection and one more certain to detect AGPL-3.0 would be to replace the current LICENSE file with a plain text one copied from https://choosealicense.com/licenses/agpl-3.0/

Closing as I don't think there's any change to be made to licensee here.
