### ISSUE TITLE
What's legally sufficient to constitute a grant of an open source software license?

### ISSUE THREAD

**Issue by benbalter** [benbalter/licensee#4]
From the readme:

> ### Why not just look at the "license" field of [insert package manager here]?
> 
> Because it's not legally binding. A license is a legal contract. You give up certain rights (e.g., the right to sue the author) in exchange for the right to use the software.
> 
> Most popular licenses today _require_ that the license itself be distributed along side the software. Simply putting the letters "MIT" or "GPL" in a configuration file doesn't really meet that requirement.
> 
> Not to mention, it doesn't tell you much about your rights as a user. Is it GPLv2? GPLv2 or later? Those files are designed to be read by computers (who can't enter into contracts), not humans (who can). It's great metadata, but that's about it.
> ### What about looking to see if the author said something in the readme?
> 
> You could make an argument that, when linked or sufficiently identified, the terms of the license are incorporated by reference, or at least that the author's intent is there. There's a handful of reasons why this isn't ideal. For one, if you're using the MIT or BSD (ISC) license, along with a few others, there's templematic language, like the copyright notice, which would go unfilled.
> ### What about checking every single file for a copyright header?
> 
> Because that's silly in the context of how software is developed today. You wouldn't put a copyright notice on each page of a book. Besides, it's a lot of work, as there's no standardized, cross-platform way to describe a project's license within a comment.
> 
> Checking the actual text into version control is definitive, so that's what this project looks at.
## The question

There's a continuum, with the full text of the license being checked into version control on one end, and a non-linked license abbreviation (e.g., "license: MIT") on the other. Which is sufficient to grant a license? Is there any precedence?
1. Full text of the license in version control
2. `LICENSE` file with the license name or abbreviation
3. `README` which references the license name or abbreviation
4. `README` which links to the full license text

**Comment by aws-dpt** [comment]
@nunobrito I'd buy that for most licenses. If I say the license is Apache, you should ask which version. The GPL family of licenses though specifically say that you can say 'GPL' and it means the user can choose their version. 

@benbalter Your answer to not putting source headers on files is pretty weak :) Seems to be "It's silly (cf: unrelated example) & it's a lot of work". Rather than trying to argue that one, you could be pointing out that licensee's job is to identify the general licensing of the package as a whole, not every license that applies to each individual file (which will often vary across the software).

**Comment by hyandell** [comment]
@nunobrito I'd buy that for most licenses. If I say the license is Apache, you should ask which version. The GPL family of licenses though specifically say that you can say 'GPL' and it means the user can choose their version.

@benbalter Your answer to not putting source headers on files is pretty weak :) Seems to be "It's silly (cf: unrelated example) & it's a lot of work". Rather than trying to argue that one, you could be pointing out that licensee's job is to identify the general licensing of the package as a whole, not every license that applies to each individual file (which will often vary across the software).

**Comment by nunobrito** [comment]
Hi @hyandell, can you provide a link to:
> The GPL family of licenses though specifically say that you can say 'GPL' and it means the user can choose their version.

Mostly for my own reference when documenting licenses in the future. Thanks.

**Comment by hyandell** [comment]
See the 2nd paragraph in section 14 of the GPL 3.0 (section 9 in GPL 2.0):

"Each version is given a distinguishing version number. If the Program specifies that a certain numbered version of the GNU General Public License “or any later version” applies to it, you have the option of following the terms and conditions either of that numbered version or of any later version published by the Free Software Foundation. If the Program does not specify a version number of the GNU General Public License, you may choose any version ever published by the Free Software Foundation. "

**Comment by nunobrito** [comment]
:thumbsup: Thanks Henri, this was right in front of my eyes and couldn't see it. Will start documenting it that way when applicable.
