### ISSUE TITLE
TextMate bundles license

### ISSUE THREAD

**Issue by pchaigno** [benbalter/licensee#58]
Nearly all TextMate bundles have [the following license](https://github.com/sublimehq/Packages/blob/master/LICENSE):

> Permission to copy, use, modify, sell and distribute this
    software is granted. This software is provided "as is" without
    express or implied warranty, and with no claim as to its
    suitability for any purpose.

> An exception is made for files in readable text which contain their own license information, or files where an accompanying file exists (in the same directory) with a “-license” suffix added to the base-name name of the original file, and an extension of txt, html, or similar. For example “tidy” is accompanied by “tidy-license.txt”.

Would you consider recognizing this license (even if it has a quite specific use)?

**Comment by benbalter** [comment]
I'm all for adding additional licenses (FWIW the PR would need to be to choosealicene.com, we just vendor their license information), but i'm not sure that adding Textmate detection tells the user much more than they already know.

Yes, we could identify the Textmate license as the primary license, but it feels a bit like a meta license explaining the obvious: "An exception is made for files in readable text which contain their own license information". If half the project is GPL via file headers, but it contains the textmate license, we'd be doing the user a disservice by saying `textmate` as the license, rather than `other` which would require human intervention, the desired outcome IMHO.

**Comment by pchaigno** [comment]
Hum, I see. I hadn't thought this through, identifying it as a TextMate license would be wrong.

I guess my real issue here is that I'd like to identify these licenses as being all the same to whitelist them. Currently we'd need to go through all the repositories manually to whitelist them.

It would be great if Licensee could return something like `license [hash of the LICENSE file] unrecognized`. It would make it possible to recognize this kind of customized/meta license :-)
What do you think?
