### ISSUE TITLE
Examples of licensed projects not detected by licensee

### ISSUE THREAD

**Issue by bkeepers** [benbalter/licensee#88]
All of [these projects](https://gist.github.com/bkeepers/8c003ed1aa2da39743ac) on GitHub are not detected by licensee, but there is Good Reason™ to believe that they are actually licensed. There's also a Good Reason™ that most of them aren't detected by licensee, but I thought there might be some patterns in there that we are missing.

**Comment by Wuzzy2** [comment]
Some patterns I found:

* License as part of the readme file (VERY common, but not trivial to detect)
* `COPYING` file (VERY common, as far I know this is generally considered to be a valid synonym for `LICENSE`)
* `LICENSE` or `COPYING` with a file name suffix
    * `.txt`
    * `.md`
    * (other) (rare)

Scannable metadata files which may include license information:
* `bower.json` (example: https://github.com/webcomponents/webcomponentsjs/blob/master/bower.json)
* `package.json` (example: https://github.com/TooTallNate/node-bindings/blob/master/package.json)
* `PKG-INFO` (example: https://github.com/RDFLib/pyrdfa3; no idea where this file comes from)
* Files with suffix `.cabal`. This comes from Cabal, a package manager for programs written in Haskell. Specification: https://www.haskell.org/cabal/

Implementing scanning those metadata files will probably be different since these files usually follow a strict syntax. I think doing reserach on other metadata files (esp. programming language specific ones) can yield some helpful results as these can be a way to unambigiously specify a license.

Unusual files (only seen once):
* https://github.com/OpenKinect/libfreenect uses `GPL2` and `APACHE20` as files
* `LICENSE.markdown`

Oddly, there seem to be some projects on the list with a `LICENSE` file but they are still on the list. Example:
* https://github.com/square/cubism

**Comment by benbalter** [comment]
> All of these projects on GitHub are not detected by licensee

Some of these are now detected. If you'd like, you can use the following script help diagnose:

```ruby
#!/usr/bin/env ruby

require 'open-uri'
require 'fileutils'

url = "https://gist.githubusercontent.com/bkeepers/8c003ed1aa2da39743ac/raw"
repos = open(url).read.split("\n")

temp_dir = File.expand_path "./tmp", File.dirname(__FILE__)

repos.each do |repo|
  path = File.join temp_dir, repo
  FileUtils.rm_rf path
  FileUtils.mkdir_p File.dirname(path)
  license_file = matched_file = nil

  begin
    Timeout::timeout(5) do
      puts "#{repo}:"
      system "git clone --depth 1 --quiet https://github.com/#{repo} #{path}"
      system "bin/licensee #{path}"
    end
  rescue Timeout::Error
    puts "Ain't nobody got time for that. Moving on."
  end

  puts ""
end

puts "Cleaning up..."
FileUtils.rm_rf temp_dir

```

**Comment by benbalter** [comment]
@Wuzzy2 Thanks for all this. Responding in line below.

> License as part of the readme file

This can be turned on. See https://github.com/benbalter/licensee/blob/master/docs/customizing.md#matching-project-readme-license-references.

> COPYING file, LICENSE or COPYING with a file name suffix

This is currently supported.

> Scannable metadata files which may include license information:

Currently Ruby and Node support can be turned on. See https://github.com/benbalter/licensee/blob/master/docs/customizing.md#matching-package-manager-metadata. I'd be glad to add review a PR to add support for other package managers.

> GPL2 and APACHE20 as files

We currently don't support those file names. We *could* but I'm hesitant to, because I'd prefer we push the community towards consistency, rather than support every possible way to represent a license.

> Oddly, there seem to be some projects on the list with a LICENSE file but they are still on the list. Example:

This is an example of https://github.com/benbalter/licensee/issues/103.

**Comment by Wuzzy2** [comment]
> > GPL2 and APACHE20 as files

> We currently don't support those file names. We could but I'm hesitant to, because I'd prefer we push the community towards consistency, rather than support every possible way to represent a license.

I agree, this practice is very obscure and I only saw it once.
